### PR TITLE
Feature branch

### PR DESCRIPTION
**Pull request by mcastorena0316**
Hi, we would like to ask for a code review, we think we already have all the requirements fullfilled.

### CODE REVIEW

**Comment by ebukaume** [comment]
## Changes Required! :stop_sign: 

Hi @mcastorena0316  and @ermin-cahtarevic :wave: 

Nice work so far :+1: . Let's quickly make these changes so we can move forward :arrow_forward: 

**Nav Bar**
- [ ] The NY Times logo should be a link.

**Theory of inflation section**
- [ ] You should not use a screenshot for this section. You may use images for the pictures but the texts **must not** be screenshots.

**Others**
- [ ] Your HTML document contain validation errors. _Use [this service](https://validator.w3.org/nu/#textarea) to check and fi the errors._

[OPTIONAL]
You may want to review and fix this blunder in your README.
readme-bug

**Please submit another code review after fixing these issues.**

Happy Coding :v: 
**Ebuka Umeokonkwo**
 [Github](https://github.com/ebukaume) | [Linkedin](https://www.linkedin.com/in/ebukaume) | [Slack](https://app.slack.com/team/UFDKXE68L) | [Twitter](https://twitter.com/ebukaume)

**Comment by mcastorena0316** [comment]
Hi i think we already fix all the mistakes and recomendations you told us. Thank you!

**Comment by ebukaume** [comment]
## Changes Required! :stop_sign: 

Hi team! :wave: 

Nice work implementing most of the requested changes, but it appears you forgot to make the NY Time logo to be a link.
review-NY times


**Please let's do this and submit another code review request.**

Happy Coding :v: 
**Ebuka Umeokonkwo**
 [Github](https://github.com/ebukaume) | [Linkedin](https://www.linkedin.com/in/ebukaume) | [Slack](https://app.slack.com/team/UFDKXE68L) | [Twitter](https://twitter.com/ebukaume)

**Comment by ermin-cahtarevic** [comment]
We had already made all the changes, but we forgot to update the live version of the site. And now we submitted a new code review

**Review by Redvanisation — APPROVED** [review]
### Hello team 🌟 

### _Nice work on this project, it seems that you guys have met the requirements so I am approving your project. 👍_ 

### You may merge to master and submit a project completion form. 🚀 

### Good luck! 🍀

**Pull request merged**
